ecommerceproject/cart/urls.py
from django.urls import path
from.import views
app_name='cart'
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name="add_cart"),
    path('',views.cart_detail,name="cart_detail"),
    path('remove/<int:product_id>/',views.cart_remove,name="cart_remove"),
    path('full_remove/<int:product_id>/',views.full_remove,name="full_remove"),
]

ecommerceproject/ecommerceapp/urls.py
from django.urls import path
from . import views
app_name = 'ecommerceapp'
urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.PrdCatDetail,name='PrdCatDetail')

]

ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from ecommerceapp import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',views.home,name='home')
    path('ecommerceapp/',include('ecommerceapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include("cart.urls")),




]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerceproject/search_app/urls.py
from django.urls import path
from.import views
app_name="search_app"


urlpatterns=[
    path('',views.searchResult,name='searchResult'),
]

ecommerceproject/cart/models.py
from django.db import models
from ecommerceapp.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price*self.quantity
    def __str__(self):
        return self.product

ecommerceproject/ecommerceapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    des=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def get_url(self):
        return reverse("ecommerceapp:products_by_category",args=[self.slug])
    def __str__(self):
        return'{}'.format(self.name)



class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    des = models.TextField(blank=True)
    image = models.ImageField(upload_to='product', blank=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse("ecommerceapp:PrdCatDetail",args=[self.category.slug,self.slug])

    def __str__(self):
        return '{}'.format(self.name)

ecommerceproject/search_app/models.py
from django.db import models

# Create your models here.

ecommerceproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecommerceapp.models import Product
from.models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save();
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
                    product=product,
                    quantity=1,
                    cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,"cart.html",dict(cart_items=cart_items,total=total,counter=counter))


def cart_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity>1:
        cart_item.quantity-=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')
def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerceproject/ecommerceapp/views.py
from django.http import HttpResponse
from .models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage
from django.shortcuts import render,get_object_or_404

# Create your views here.
def home(request):
    return HttpResponse("hellooo")


def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category':c_page,'products':products})

def PrdCatDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
            raise e
    return render(request,'product.html',{'product':product})

ecommerceproject/search_app/views.py
from django.shortcuts import render
from ecommerceapp.models import Product
from django.db.models import Q


def searchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(des__contains=query))
    return render(request,"search.html",{'query':query,'products':products})

ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" >
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>
<div>
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}" ></script>
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        Welcome to the cart store where you can buy awesome items.

{% endblock %}
{% block title %}
    Cart -Shop Your Favourite!!!
{% endblock %}
{% block content %}
{% if not cart_items %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my_title">
                Your Shopping Cart is Empty
            </h1>
            <br>
            <p class="text-center">
                Please click<a href="{% url 'ecommerceapp:allProdCat'%}">Here</a>
            </p>
        </div>
    </div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart

        </h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="s">Your Items</th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src={{cart_item.product.image.url}} class="float-left rounded custom_image" style="width:50px;height:50px;"></a>
                </td>
                <td class="text-left">

                    {{cart_item.product.name}}
                    <br>
                    SKU:{{cart_item.product.id}}
                    <br>
                    Unit price :{{ cart_item.product.price}}
                    QTY:{{cart_item.quantity}} * $ {{cart_item.product.price}}
                </td>
                <td>${{crt_item.sub_total}}</td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a" > <i class="fas fa-plus custom_icon"></i></a>&nbsp;
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_icon" ><i class="fas fa-minus custom_icon"></i></a>&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>

                </td>
                {% else %}
                <td>
                     &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a" ><i class="fas fa-minus custom_icon"></i></a>&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please review Your shopping cart items before proceeding with the order payment.
                </td>
            </tr>
            <tr>
            <td class="text-left">
                Your total is <strong>${{ total }}</strong>
            </td></tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{%url 'ecommerceapp:allProdCat'%}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping With Us</a>
</div>
    </div>
</div><br>
{% endif %}
{% endblock %}

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.des |truncatewords:155 }}
    {% else %}
        Welcome to the cart store where you can buy awesome items.
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{category.name}}-Shop Cart
    {% else %}
        see our collections -Shop Cart
        {% endif %}
{% endblock %}
{% block content %}
    {% if category %}
        <div class="row my_row_class">
            <div class="mx-auto">
                <p><a href="{% url 'ecommerceapp:allProdCat' %}">Our product collections </a>>{{ category.name}}</p>
            </div>
        </div>
    {% endif %}
<div class="mx-auto">
        {% if category %}
            <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">

</div><br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.des}}</p>
</div>
{% else %}
<div>
    <center><img class="my_image my_image_padding" src="{% static 'img/shopping.png' %}" style="width:1250px;" alt=""></center>
</div>
<br>
<div>
    <h1 class="text-center my_title"> our product collections</h1>
    <p class="text-justify">super cooled collections of variety of summer clothes</p>
</div>
{% endif %}
<div class="container">
    <div class="row max-auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="width: 18rem;">
            <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" style="width:250px;height:250px;" alt="{{product.name}}">
            </a>
            <div class="card-body">
                <h4>{{product.name}}</h4>
                <p>${{product.price}}</p>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
    <div class="mx-auto">
<div class="text-center">
        {% for pg in products.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} activate {% endif %}">{{pg}}</a>
        {% endfor %}
</div>
    </div>
</div>
{% endblock %}

ecommerceproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; Avodha Training .All Rights Reserved</p>
</div>

ecommerceproject/templates/header.html
{% load static %}
<div>
    <center>
        <img src="{% static 'img/shop.png' %}" alt='this is avodha logo'>
    </center>
</div>

ecommerceproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<!--  <a class="navbar-brand" href="#">Navbar</a>-->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shop
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'ecommerceapp:allProdCat' %}">All Products</a>
            {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
            {% endfor %}
<!--          <div class="dropdown-divider"></div>-->
<!--          <a class="dropdown-item" href="#">Something else here</a>-->
<!--        </div>-->
       </li>
<!--      <li class="nav-item active">-->
<!--        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
<!--      </li>-->
        {%  if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link" href="cart:cart_details"><i class="fas fa-cart-plus">{{item_count}}</i></a>
      </li>
        {% endif %}
<!--      <li class="nav-item">-->
<!--        <a class="nav-link disabled" href="#">Disabled</a>-->
<!--      </li>-->
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>
  </div>
</nav>

<!--<nav>-->
<!--&lt;!&ndash;    <ul>&ndash;&gt;-->
<!--&lt;!&ndash;        <li><a href="{% url 'ecommerceapp:allProdCat' %}">All products</a></li>&ndash;&gt;-->
<!--&lt;!&ndash;        {% for cat in links %}&ndash;&gt;-->
<!--&lt;!&ndash;            <li><a href="{{cat.get_url}}">{{cat.name}}</a></li>&ndash;&gt;-->

<!--&lt;!&ndash;        {% endfor %}&ndash;&gt;-->
<!--&lt;!&ndash;        <li>your cart</li>&ndash;&gt;-->
<!--&lt;!&ndash;    </ul>&ndash;&gt;-->
<!--</nav><br>-->

ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.des|truncatewords:155}}
{% endblock %}
{% block title %}
    {{product.name}}-Shop Cart
{% endblock %}
{% block content %}
<div class="row my_prod_row_class">
    <div class="mx-auto">
        <p><a href="{% url 'ecommerceapp:allProdCat' %}">Home</a> |<a href="{{product.category.get_url}}" ></a>{{product.name}}</p>
    </div>
    <div class="container">
        <br>
        <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div style="min-width:18rem;">
                <img src="{{product.image.url}}" alt="{{product.name}}" style="width:500px;height:500px;">
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 ">
            <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p class="my_title">Product Description</p>
            <p class="text-justify my_prod_text">{{product.des}}</p>
            {% if product.stock <= 0 %}
                <p class="text-justify my_prod_text"><b> Out Of Stock  </b></p>
            {% else %}
                <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add To Cart</a>
            {% endif %}

            </div>

            </div>
        </div>

    </div>
</div>

{% endblock %}

ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.des|truncatewords:155}}
{% endblock %}
{% block title %}
    {{product.name}}-Shop Cart
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text"> You have Searched for: {{query}}</p>
</div>
<div class="container">
    <div class="row max-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="width: 18rem;">
            <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" style="width:250px;height:250px;" alt="{{product.name}}">
            </a>
            <div class="card-body">
                <h4>{{product.name}}</h4>
                <p>${{product.price}}</p>
            </div>
        </div>
    </div>
    {% empty %}
    <div class="row mx-auto">
        <p class="text-center my_search_text">0 results found.</p>

    </div>
    {% endfor %}
    </div>
</div>
{% endblock %}